// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuqxwwajxsruyrvdlksn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cXh3d2FqeHNydXlydmRsa3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjg3MTUsImV4cCI6MjA2OTIwNDcxNX0.X0UdyWlTQufIJaLOxP94i0VRRiHXTpXvcgKriJgmph8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});